"""add order_reports table

Revision ID: 6897e7e5204a
Revises: a1b2c3d4e5f6
Create Date: 2025-12-15 08:47:09.786175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6897e7e5204a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаём таблицу order_reports
    op.create_table(
        'order_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('report_at', sa.Date(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('count_product', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем таблицу order_reports
    op.drop_table('order_reports')
    # ### end Alembic commands ###
